services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: testedev
      POSTGRES_USER: kauah
      POSTGRES_PASSWORD: segredo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - postgres
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    image: node:20
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  postgres_data:
